[WIP] GCP Modules
argonautdev/tf-modules pull request #50
Opened 2022-06-15 12:20 UTC by pk0331

1. VPC
   2. GKE

2022-07-05 16:59 UTC, suryaoruganti commented on modules/gcp/bastion/variables.tf
> +  default     = "ubuntu-1804-lts"
should use the 2204 image

2022-07-05 17:20 UTC, pk0331 commented on modules/gcp/bastion/variables.tf
> +}
It's just not mentioned in description, but it is actually working if i pass "pd-balanced".

2022-07-18 04:21 UTC, PrashantRaj18198 commented
Please update the naming convention for the folders to strictly use lowercase `snake_case`.

2022-07-18 04:32 UTC, PrashantRaj18198 requested changes

2022-07-18 04:32 UTC, PrashantRaj18198 commented on modules/gcp/vpc/variables.tf
> +variable "project_id" {
Always accept a set of tags/labels to all gcp modules. This is added all gcp resource/module block in the terraform

2022-07-19 06:38 UTC, PrashantRaj18198 requested changes

2022-07-19 06:38 UTC, PrashantRaj18198 commented on modules/gcp/vpc/variables.tf
> +  type        = list(map(string))
Define the proper type please for your variables.

2022-07-19 06:38 UTC, PrashantRaj18198 commented on modules/gcp/vpc/variables.tf
> +  type        = list(map(string))
It shouldn't be `list(map(string))`, it should be `list(object({ ... myvars }))`

2022-07-19 06:38 UTC, PrashantRaj18198 commented on modules/gcp/vpc/variables.tf
> +variable "nats" {
Can't we have these in the variable type?

2022-07-19 06:41 UTC, PrashantRaj18198 commented on gcp-main (2).tf
> +           subnet_flow_logs      = "false"
Is it necessary of this to be a string encoded boolean? Can we change this to bool values and do the encoding in the terraform module itself?

2022-07-19 08:59 UTC, PrashantRaj18198 commented on modules/gcp/vpc/variables.tf
> +}
Remove this `secondary_ranges` since it is not vpc specific. `secondary_ranges` should be created by the resources right?

2022-07-20 02:01 UTC, pk0331 commented
Closing this branch, kind of messed up

2022-07-20 02:01 UTC, closed without merging