GKE, VPC modules for GCP
argonautdev/tf-modules pull request #59
Opened 2022-08-04 05:07 UTC by pk0331

GKE Modules for VPC, GKE

2022-08-04 05:17 UTC, PrashantRaj18198 requested changes
Minor changes please 🙏

2022-08-04 05:17 UTC, PrashantRaj18198 commented on modules/gcp/gke/main.tf
> +  node_pools_labels         = var.node_pools_labels
the `default_labels` should be applied to all the resources that support labels. We'll need to add `default_labels` to each `node_pool`.

2022-08-04 05:17 UTC, PrashantRaj18198 commented on modules/gcp/vpc/variables.tf
> +variable "project_id" {
Does vpc not have resources that support `labels`?

2022-08-05 05:27 UTC, PrashantRaj18198 commented on modules/gcp/gke/main.tf
> +  node_pools_labels         = var.node_pools_labels
already present in `cluster_resource_labels` so should not be required for `node_pools_labels`.

2022-08-05 05:28 UTC, PrashantRaj18198 commented on modules/gcp/vpc/variables.tf
> +variable "project_id" {
Confirmed on call by @pk0331 that `labels` aren't present for vpc.

2022-08-26 16:15 UTC, suryaoruganti approved these changes

2022-08-26 16:15 UTC, merged